development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  lunchon_development
  pool: 5
  username: root
  password: root
  # socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  lunchon_test
  pool: 5
  username: root
  password: root
  # socket: /tmp/mysql.sock