development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  lunchon_development
  pool: 5
  username: lunchon
  password: lunchon123
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  lunchon_development
  pool: 5
  username: lunchon
  password: lunchon123
  socket: /tmp/mysql.sock
